
/*
ALTER TABLE TB_ACCOUNT ADD STATUS BIT NOT NULL
ALTER TABLE TB_ACCOUNT ADD CATEGORY BIT

ALTER TABLE TB_ACCOUNT
ALTER COLUMN CATEGORY NVARCHAR(10)

EXEC sp_rename 'TB_POST.ENTERPRISE_NAME', 'ID_EMPLOYER', 'COLUMN';

ALTER TABLE TB_POST 
ALTER COLUMN ID_EMPLOYER NVARCHAR(10)

ALTER TABLE TB_POST
DROP CONSTRAINT FK__TB_POST__ID_ADDR__38996AB5

ALTER TABLE TB_POST
ADD FOREIGN KEY (ID_EMPLOYER) REFERENCES TB_EMPLOYER(ID_EMPLOYER)

select CONSTRAINT_NAME
from INFORMATION_SCHEMA.TABLE_CONSTRAINTS
where TABLE_NAME = 'TB_POST'

DROP TABLE TB_POST
DROP TABLE TB_JOBSEEKER
DROP TABLE TB_EMPLOYER
DROP TABLE TB_ACCOUNT
DROP TABLE TB_CATEGORY_JOB
*/