USE UngDungTimViecLam
GO
INSERT INTO TB_ACCOUNT(ID_ACCOUNT,USERNAME,PASSWORD,ACCESSER,STATUS) VALUES
('AA001','ADMIN','ADMIN',NULL,1),
('AE001','LHM','1234',1,1),
('AJ001','LVN','1234',0,1)

INSERT INTO TB_PROFILE(ID_PROFILE, IMAGE, NAME, CITY, PHONE_NUMBER, EMAIL, FACEBOOK, WEBSITE) VALUES
('PF001',(SELECT * FROM OPENROWSET(BULK N'C:\Users\lehon\Desktop\HK4\PBL3_UngDungTimViecLam\Image\lop.jpg', SINGLE_BLOB) as IMAGE),'MINH','HA TINH','0763034216','LHM2K1@GMAIL.COM',NULL,NULL),
('PF002',(SELECT * FROM OPENROWSET(BULK N'C:\Users\lehon\Desktop\HK4\PBL3_UngDungTimViecLam\Image\lop.jpg', SINGLE_BLOB) as IMAGE),'LHM','HA TINH','0763034216','LHM2K1@GMAIL.COM',NULL,NULL)

INSERT INTO TB_EMPLOYER(ID_EMPLOYER, ID_ACCOUNT, ID_PROFILE) VALUES
('EM001', 'AE001', 'PF001')


--DELETE FROM TB_ACCOUNT